export const exports = [
	'lib/index.ts',

	// deep imports - these do not include $lib/earbetter or $lib/projects
	'lib/ac.ts',
	'lib/colors.ts',
	'lib/dom.ts',
	'lib/emoji.ts',
	'lib/entity.ts',
	'lib/exports.ts',
	'lib/helpers.ts',
	'lib/id.ts',
	'lib/InitMidiButton.svelte',
	'lib/InstrumentControl.svelte',
	'lib/IntervalsInput.svelte',
	'lib/index.ts',
	'lib/midi_access.ts',
	'lib/midi_helpers.ts',
	'lib/MidiInput.svelte',
	'lib/MidiRangeControl.svelte',
	'lib/music.ts',
	'lib/Piano.svelte',
	'lib/piano.ts',
	'lib/PianoKey.svelte',
	'lib/play_note.ts',
	'lib/SelectNotesControl.svelte',
	'lib/storage.ts',
	'lib/TextBurst.svelte',
	'lib/url.ts',
	'lib/VolumeControl.svelte',
	'lib/WebMIDI.ts',
];
