export const exports = [
	'lib/index.ts',

	// deep imports - these do not include $lib/earbetter or $lib/projects
	'ac.ts',
	'colors.ts',
	'emoji.ts',
	'entity.ts',
	'exports.ts',
	'helpers.ts',
	'id.ts',
	'InitMidiButton.svelte',
	'InstrumentControl.svelte',
	'IntervalsInput.svelte',
	'index.ts',
	'midi_access.ts',
	'midi_helpers.ts',
	'MidiInput.svelte',
	'MidiRangeControl.svelte',
	'music.ts',
	'Piano.svelte',
	'piano.ts',
	'PianoKey.svelte',
	'play_note.ts',
	'SelectNotesControl.svelte',
	'storage.ts',
	'test.ts',
	'TextBurst.svelte',
	'url.ts',
	'VolumeControl.svelte',
	'WebMIDI.ts',
];
